trigger:
 branches:
  include:
  -main

pool:mypool

stages:
  - stage: 
    displayName: terraformstage
    jobs:
      - job: 
        displayName: myjob
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Devops_service'
              backendAzureRmStorageAccountName: 'mystoagebhakua'
              backendAzureRmContainerName: 'mycontainer'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Devops_service'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'Devops_service'