trigger:
 - feature/*
 - main

pool: mypool

stages:
  - stage: Plan
    displayName: terraformplan
    jobs:
      - job: 
        displayName: myjob
        steps:
          - task: TerraformInstaller@1
            displayName: terraforminstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: terraforminit
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'newservice'
              backendAzureRmStorageAccountName: 'mystoagebhakua'
              backendAzureRmContainerName: 'mycontainer'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTask@5
            displayName: terraformvalidate
            inputs:
              provider: 'azurerm'
              command: 'validate'
          - task: TerraformTask@5
            displayName: terraformplan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'newservice'
 
  - stage: apply
    condition: 
    displayName: terraformapply
    jobs:
      - job: 
        displayName: myjob
        steps:
          - task: TerraformInstaller@1
            displayName: terraforminstall
            inputs:
              terraformVersion: 'latest'
              
      - job: 
        displayName: applyjob
        steps:
          - task: TerraformTask@5
            displayName: terraform apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'newservice'