trigger:
 branches:
  include:
  - main

pool: mypool

stages:
  - stage: 
    displayName: terraformstage
    jobs:
      - job: 
        displayName: myjob
        steps:
          - task: TerraformInstaller@1
            displayName: terraforminstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: terraforminit
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'newservice'
              backendAzureRmStorageAccountName: 'mystoagebhakua'
              backendAzureRmContainerName: 'mycontainer'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTask@5
            displayName: terraformvalidate
            inputs:
              provider: 'azurerm'
              command: 'validate'
          - task: TerraformTask@5
            displayName: terraformplan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'newservice'
          - task: TerraformTask@5
            displayName: terraform apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'newservice'